# -*- coding: utf-8 -*-
"""Copy of package_kivymd_apps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vpzH3JP7hmk7yu9RkWn2t2hOYrMYAERX

# Packaging applications for android with buildozer

## Step 1: Install buildozer dependencies

Run the following cell.
"""

!wget https://github.com/HeaTTheatR/KivyMD-data/raw/master/install-kivy-buildozer-dependencies.sh
!chmod +x install-kivy-buildozer-dependencies.sh

!./install-kivy-buildozer-dependencies.sh

"""## Step 2: Install some updates and packages vital for packaging"""

!sudo apt update
!sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
!pip install --upgrade Cython==0.29.19 virtualenv
!sudo apt upgrade

"""## Step 3: Install dependencies and Clean"""

!pip install -U cython # cython-3.0.2
!pip install --upgrade pygame-ce pyjnius
!rm -rf sample_data buildozer get-pip.py install-kivy*

"""## Step 4: Create the spec file"""

!buildozer init

"""## Step 5: Upload the files

Upload the files main.py and main.kv
Click on the file icon to the left of the screen, right click and click upload.

## Step 6: Run buildozer.
Make sure to accept the terms and conditions. The process could take up to 15 minutes so be patient.
"""

!buildozer -v android debug

"""## Step 7: Download the apk file."""